name = "king-surya-files"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "king-surya-files-bucket"
